version: "2.2"
services:
  docker_csc496:
    extends:
      file: docker-compose.yml
      service: docker_csc496
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    #  - ROS_MASTER_URI=http://localhost:11311
    #  - ROS_HOSTNAME=localhost     
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw

